jwt.private.key=classpath:app.key
jwt.public.key=classpath:app.pub

spring.application.name=pubonline-api

spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
spring.datasource.url=jdbc:postgresql://postgres-db-dev.cr46820waaob.us-east-2.rds.amazonaws.com:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=placebo*03

spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=false
spring.jpa.generate-ddl=false
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

auth.jwt.token.secret=
auth.jwt.token.expiration=1
auth.jwt.refresh-token.expiration=2



