jwt.private.key=classpath:app.key
jwt.public.key=classpath:app.pub

spring.application.name=pubonline-api

spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
spring.datasource.url=${{ secrets.SPRING_DATASOURCE_URL }}
spring.datasource.username=${{ secrets.SPRING_DATASOURCE_USERNAME }}
spring.datasource.password=${{ secrets.SPRING_DATASOURCE_PASSWORD }}

spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

auth.jwt.token.secret=
auth.jwt.token.expiration=1
auth.jwt.refresh-token.expiration=2



