services:
  pubonline-api:
    container_name: pubonline-api
    image: rformaggini/pubonline-api:latest
    environment:
      SERVER_PORT: 8080
    ports:
      - 80:8080
    networks:
      - pg-db-network
    restart: always

  pubonline-app:
    container_name: pubonline-app
    image: rformaggini/pubonline-app:latest
    ports:
      - 4200:4200
    depends_on:
      - pubonline-api
    networks:
      - pg-db-network
    restart: always
    links:
      - pubonline-api

networks:
  pg-db-network:
    driver: bridge