name: Deploy on DEVELOP environment

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install and configuring java
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "21"

      - name: Build project
        run: mvn clean install -DskipTests && ls

      - name: Login Docker Hub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build Docker Image
        run: docker build -t rformaggini/pubonline-api .

      - name: Push Image Docker
        run: docker push rformaggini/pubonline-api



