name: Deploy on DEVELOP environment

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install and configuring java
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "21"

      - name: Build project
        run: mvn clean install -DskipTests && ls

      - name: Send jar to EC2
        uses: appleboy/scp-action@master
        with:
          host: ec2-3-141-21-218.us-east-2.compute.amazonaws.com
          username: ec2-user
          key: ${{ secrets.KEY_PUB_ONLINE_API }}
          port: 22
          source: "./target/pubonline-api-0.0.1-SNAPSHOT.jar"
          target: "/home/ec2-user"
